//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PongChain1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetLedger
    {
        public int Id { get; set; }
        public bool Active { get; set; }
        public int PlayersId { get; set; }
        public decimal Transaction { get; set; }
        public decimal CurrentTotal { get; set; }
        public Nullable<int> GamesId { get; set; }
        public string Description { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
