//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PongChain1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int WinnerPlayersId { get; set; }
        public int LoserPlayersId { get; set; }
        public int WinnerScore { get; set; }
        public int LoserScore { get; set; }
        public Nullable<decimal> WinMoney { get; set; }
        public Nullable<decimal> LoseMoney { get; set; }
        public bool IsTournamentGame { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
